import 'dotenv/config';
import argon2 from 'argon2';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from './generated/client.js';

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error('DATABASE_URL is required to run seed');
}

const adapter = new PrismaPg({ connectionString: databaseUrl });
const prisma = new PrismaClient({ adapter });

async function main(): Promise<void> {
  const ownerEmail = process.env.SEED_OWNER_EMAIL ?? 'owner@parkcore.dev';
  const ownerPassword = process.env.SEED_OWNER_PASSWORD ?? 'OwnerPassw0rd!123';
  const passwordHash = await argon2.hash(ownerPassword);

  const owner = await prisma.user.upsert({
    where: { email: ownerEmail },
    update: {
      name: 'Demo',
      lastName: 'Owner',
      phone: '1234567890',
    },
    create: {
      email: ownerEmail,
      passwordHash,
      name: 'Demo',
      lastName: 'Owner',
      phone: '1234567890',
    },
  });

  let parking = await prisma.parking.findFirst({
    where: {
      ownerId: owner.id,
      title: 'Central Parking Demo',
    },
  });

  parking ??= await prisma.parking.create({
    data: {
      title: 'Central Parking Demo',
      description: 'Demo parking generated by seed script',
      address: '123 Main Street',
      image: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a',
      hourlyRateCents: 1500,
      currency: 'USD',
      capacity: 30,
      lat: 40.7128,
      lng: -74.006,
      owner: { connect: { id: owner.id } },
    },
  });

  console.log(`Seed completed. Owner: ${owner.email}. Parking: ${parking.title}`);
}

main()
  .catch((error: unknown) => {
    console.error('Seed failed');
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
